## 
POST http://localhost:3000/users/
Content-Type: application/json

{
  "username": "tontinnn",
  "nombre": "Agustin Mulet",
  "apellidos": "Agustin Mulet",
  "email": "han_rp@hotmail.com",
  "password": "abcdef"

}